# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2026-02-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='xx',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
