# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2026-02-25 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book_xx'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='xx2',
            field=models.CharField(default='xx2', max_length=32),
        ),
    ]
