# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2026-02-25 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_book_xx2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='xx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='xx2',
        ),
    ]
